# Generated by Django 4.1.1 on 2022-11-19 16:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0009_product_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='productinfo',
            field=models.CharField(blank=True, default=' ', max_length=1200, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='description',
            field=models.CharField(blank=True, default=' ', max_length=1200, null=True),
        ),
    ]
