# Generated by Django 4.1.1 on 2023-01-14 14:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0012_alter_product_sizes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='sizes',
            field=models.CharField(blank=True, choices=[('1', 'L'), ('2', 'M'), ('3', 'S')], default='1', max_length=50, null=True),
        ),
    ]
