# Generated by Django 5.0.4 on 2024-05-10 16:34

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0018_alter_order_date_alter_product_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='date',
            field=models.DateField(default=datetime.datetime(2024, 5, 10, 22, 4, 24, 881276)),
        ),
        migrations.AlterField(
            model_name='product',
            name='productinfo',
            field=models.TextField(blank=True, default=' ', max_length=1200, null=True),
        ),
    ]
