# Generated by Django 5.0.4 on 2024-05-19 09:14

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0019_alter_order_date_alter_product_productinfo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='date',
            field=models.DateField(default=datetime.datetime(2024, 5, 19, 14, 44, 28, 572163)),
        ),
    ]
